### Numpy

- A fundamental library for scientific computing in Python.

- It provides support for arrays and materices along with a collection of mathematical functions to operate on these data structures.

In [3]:
## Importing numpy library :
import numpy as np

## Creating array using numpy
# 1D array :
arr1 = np.array([1,2,3,4,5])
print(arr1) 
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
# Creating a 1D array :
arr2 = np.array([1,2,3,4,5])

# Reshaping 1D array to 2D array (1 row , 5 columns)
arr3 = arr2.reshape(1,5)
print(arr3)
print(type(arr3))
print(arr3.shape)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [8]:
# Creating a 2D array : (2 rows , 4 columns)
arr4 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr4)
print(type(arr4))
print(arr4.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)


In [10]:
# Reshaping an array :
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
# Reshaping an array :
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [13]:
# ones() : creating a matrix of 1s with given shape 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix :
# eye() :
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
## Example of 2D array Attributes :

arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print("Array :",arr)
print("\nShape :",arr.shape)
print("Number of Dimension :",arr.ndim)
print("Size (number of elements) :",arr.size)
print("Data Type :", arr.dtype)
print("Item Size (in bytes) :",arr.itemsize)

Array : [[1 2 3]
 [4 5 6]]

Shape : (2, 3)
Number of Dimension : 2
Size (number of elements) : 6
Data Type : int32
Item Size (in bytes) : 4


In [23]:
## Numpy Vectorized Operations : 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element-wise Addition
print("Addition :",arr1 + arr2)

# Element-wise Subtraction
print("Subtraction :",arr1 - arr2)

# Element-wise Multiplication
print("Multiplication :",arr1 * arr2)

# Element-wise Division 
print("Division :",arr1/arr2)

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [26]:
### Universal Function
arr = np.array([2,3,4,5,6])

# Square Root
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
## Array Slicing and Indexing :
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array :\n", arr)


Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1


In [35]:
# Printing 1,6 and 12 from the array

print(arr[0][0])
print(arr[1][1])
print(arr[2][3])

1
6
12


In [38]:
# Print [ 7, 8 ]
#       [11, 12]

print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [42]:
# Print [3,4]
#       [7,8]
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [47]:
# Print [1]
#       [5]
#       [9]
print(arr[0:3,0])

[1 5 9]


In [48]:
# Modify Array Element :
print(arr)

arr[0,0] = 100
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [49]:
arr[1:,2:] = 100
print(arr)

[[100   2   3   4]
 [  5   6 100 100]
 [  9  10 100 100]]


In [50]:
## Real World Application

# Statistical Concept -- Normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data :
normalized_data = (data - mean) / std_dev
print("Normalized Data : ",normalized_data)


Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean :
mean = np.mean(data)
print("Mean :",mean)

# Median :
median = np.median(data)
print("Median :",median)

# Standard Deviation :
std_dev = np.std(data)
print("Standard Deviation :",std_dev)

# Variance :
variance = np.var(data)
print("Variance :",variance)

Mean : 5.5
Median : 5.5
Standard Deviation : 2.8722813232690143
Variance : 8.25


In [56]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Get values for numbers which are greater than 5
data[data > 5]

# Get values between 2 and 5
data[(data>2) & (data<5)]

array([3, 4])